### PR TITLE
Specific defaults compatibility 🎈 

### LINKED ISSUE #998: Bring specific-defaults feature into compatibility with sudo
It seems that I may have interpreted `man sudoers` a particular way that seems incorrect. E.g.

    Defaults:user !rootpw
    Defaults@machine rootpw

and

    Defaults@machine rootpw
    Defaults:user !rootpw

have the exact same meaning in sudo-rs (at the current state, commit 651cdcf6ebdd8819d48c56fd2d61a07add5b92a3), since we give a higher priority to user-specific `Defaults` compared to host-specific `Defaults`, but in sudo the 'later' defaults overrides the 'earlier' one.

This is based on the phrasing:

     Defaults entries are parsed in the following order: global, host, user,
     and runas Defaults first, then command defaults.  If there are multiple
     Defaults settings of the same type, the last matching setting is used.

I've reached out to Todd for clarification.

### PR DESCRIPTION
**Pull request by squell**
Tracked item number ***1000*** 🎆 🥳 🎉 

Closes #998, extends #997 (which must be merged first). This brings sudo-rs into compliance with ogsudo per correspondence with Todd. The exact precedence of specific-defaults is a bit "evolved" behaviour (I'd either prefer strict ordering, or the thing the current man sudoers describes), but it's probably better to be 100% identical here.

I've let the CI run fully on commits 536bbad .. 0d72aeb to illustrate what every change functionally does.

### CODE REVIEW

File: src/sudoers/mod.rs [hunk 1]
```diff
@@ -40,7 +40,7 @@ pub struct Error {
 ///
 /// I.e. the Setting modifications in the second part of the tuple only apply for
 /// items explicitly matched by the first part of the tuple.
-type Customiser<T> = (SpecList<T>, Vec<defaults::SettingsModifier>);
+type Customiser<Scope = ConfigScope> = (Scope, Vec<defaults::SettingsModifier>);
```
Comment (bjorn3) [inline src/sudoers/mod.rs:43]:
```suggestion
type Customiser<Scope> = (Scope, Vec<defaults::SettingsModifier>);
```

and use `Customiser<ConfigScope>` at the only place where you used plain `Customiser`.

**Review by bjorn3 — APPROVED** [review]
