### PR TITLE
Debounce bell

### LINKED ISSUE #1180: Bell not working with fingerprint
**Describe the bug**
I'm trying to use the bell flag to automatically play a sound when authentication is required. However, it doesn't work as expected with fingerprint authentication. The sound only plays after three failed fingerprint attempts, when the system falls back to asking for the password.

**To Reproduce**
1. Run `sudo -B echo hey`
2. Bug occurs

**Expected behavior**
It should play a bell if sudo asks for a fingerprint too.

**Environment (please complete the following information):**
 - Linux distribution: NixOS 25.11 (Xantusia)
 - `sudo-rs` commit hash: `17ead4e`

### PR DESCRIPTION
**Pull request by squell**
Closes #1180

This also removes the bell being run with `askpass`. I'm not sure what setting askpass+bell makes sense, or will actually result in a bell being heard (since we're not opening a TTY), but in any case ogsudo doesn't ring a bell if I use systemd-ask-password. Maybe we should even emit an error that `--bell` and `-A` are incompatible (but then we should probably also emit an error that `-A` and `-p` are incompatible, and so on and on, that would be a different issue)

Never thought I would want to use `Cell` for something, but in this case it does precisely the trick.

Basically, whenever we open the TTY in converse, that means we're going to be wanting the user's attention for something, and that's the moment to ring the bell *once*.

### CODE REVIEW

File: src/pam/converse.rs [hunk 1]
```diff
@@ -97,7 +97,7 @@ pub struct CLIConverser {
     pub(super) name: String,
     pub(super) use_askpass: bool,
     pub(super) use_stdin: bool,
-    pub(super) bell: bool,
+    pub(super) bell: std::cell::Cell<bool>,
```
Comment (bjorn3) [inline src/pam/converse.rs]: nit: `use std::cell::Cell;`

Comment (squell) [reply src/pam/converse.rs]: That's more typing.
