### PR TITLE
Work-around for broken test in ogsudo

### LINKED ISSUE #1517: Failure in ogsudo compliance tests
As observed [here](https://github.com/trifectatechfoundation/sudo-rs/actions/runs/23338333515/job/67886497000).

The error messages seem to indicate the test is working fine, but suggest a bug in ogsudo (in both test cases the file name is missing from the error message). Since we only run the `og` compliance tests if something changes in the test framework, it is quite possible that Debian stable has backported a sudo security fix recently that introduces this.

```
---- sudo::sudoers::includedir::ignores_and_warns_about_file_with_bad_ownership stdout ----

thread 'sudo::sudoers::includedir::ignores_and_warns_about_file_with_bad_ownership' (150077) panicked at sudo-compliance-tests/src/sudo/sudoers/includedir.rs:157:5:
"sudo:  is owned by uid 1000, should be 0" did not contain "/etc/sudoers.d/a is owned by uid 1000, should be 0"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- sudo::sudoers::includedir::ignores_and_warns_about_file_with_bad_perms stdout ----

thread 'sudo::sudoers::includedir::ignores_and_warns_about_file_with_bad_perms' (150277) panicked at sudo-compliance-tests/src/sudo/sudoers/includedir.rs:124:5:
"sudo:  is world writable" did not contain "/etc/sudoers.d/a is world writable"
```

### PR DESCRIPTION
**Pull request by squell**
Closes #1517

### CODE REVIEW

File: test-framework/sudo-compliance-tests/src/sudo/sudoers/includedir.rs [hunk 1]
```diff
@@ -117,7 +117,12 @@ fn ignores_and_warns_about_file_with_bad_perms() {
 
     output.assert_success();
     let diagnostic = if sudo_test::is_original_sudo() {
-        format!("{ETC_DIR}/sudoers.d/a is world writable")
+        // FIXME: a recent change in ogsudo has broken this error message,
+        // and this regression has sadly also been back-ported into trixie.
+        // the full error message should be:
```
Comment (bjorn3) [inline test-framework/sudo-compliance-tests/src/sudo/sudoers/includedir.rs:124]: Can you link to the upstream issue?

**Review by bjorn3 — APPROVED** [review]
with the link added

File: test-framework/sudo-compliance-tests/src/sudo/sudoers/includedir.rs (hunk 1 above)
Comment (squell) [reply test-framework/sudo-compliance-tests/src/sudo/sudoers/includedir.rs:124]: Sure

Comment (squell) [reply test-framework/sudo-compliance-tests/src/sudo/sudoers/includedir.rs:124]: (Wasn't there when I made this fix since it was still bisecting)

Once merged, we should also open an issue over here (with `waiting-on-upstream` label) to track this FIXME.

Comment (squell) [reply test-framework/sudo-compliance-tests/src/sudo/sudoers/includedir.rs:124]: Opened #1520
